.TH "src Directory Reference" 3 "Fri Feb 19 2021" "S.S.E.H.C" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBai\fP"
.br
.ti -1c
.RI "directory \fBchess\fP"
.br
.ti -1c
.RI "directory \fBdatastructures\fP"
.br
.ti -1c
.RI "directory \fBmisc\fP"
.br
.ti -1c
.RI "directory \fBtests\fP"
.br
.ti -1c
.RI "directory \fBuci\fP"
.br
.in -1c
