.TH "include/datastructures Directory Reference" 3 "Mon Feb 15 2021" "S.S.E.H.C" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/datastructures Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBboard\&.hpp\fP"
.br
.ti -1c
.RI "file \fBmovegen\&.hpp\fP"
.br
.ti -1c
.RI "file \fBsearch\&.hpp\fP"
.br
.in -1c
