.TH "include/game Directory Reference" 3 "Mon Feb 15 2021" "S.S.E.H.C" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/game Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBchessboard\&.hpp\fP"
.br
.ti -1c
.RI "file \fBcmove\&.hpp\fP"
.br
.ti -1c
.RI "file \fBpieces\&.hpp\fP"
.br
.in -1c
