.TH "include Directory Reference" 3 "Mon Feb 15 2021" "S.S.E.H.C" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBai\fP"
.br
.ti -1c
.RI "directory \fBdatastructures\fP"
.br
.ti -1c
.RI "directory \fBgame\fP"
.br
.ti -1c
.RI "directory \fBmisc\fP"
.br
.ti -1c
.RI "directory \fBuci\fP"
.br
.in -1c
