.TH "include/ai/ai.hpp" 3 "Mon Feb 22 2021" "S.S.E.H.C" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/ai/ai.hpp
.SH SYNOPSIS
.br
.PP
\fC#include <limits>\fP
.br
\fC#include <chrono>\fP
.br
\fC#include <atomic>\fP
.br
\fC#include 'misc/definitions\&.hpp'\fP
.br
\fC#include 'datastructures/search\&.hpp'\fP
.br
\fC#include 'game/chessboard\&.hpp'\fP
.br
\fC#include 'game/cmove\&.hpp'\fP
.br
\fC#include 'datastructures/move_list\&.hpp'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBai\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBai::materialEvaluation\fP (\fBBoard\fP &board)"
.br
.ti -1c
.RI "int \fBai::evaluation\fP (\fBBoard\fP &board)"
.br
.ti -1c
.RI "int \fBai::flippedEval\fP (\fBBoard\fP &board)"
.br
.ti -1c
.RI "void \fBai::sendPV\fP (\fBBoard\fP &board, int depth, \fBCMove\fP pv_move, int node_count, \fBScore\fP score, std::chrono::_V2::system_clock::time_point start)"
.br
.ti -1c
.RI "\fBCMove\fP \fBai::rootMove\fP (\fBBoard\fP &board, int depth, std::atomic< bool > &stop, \fBScore\fP &out_score, \fBCMove\fP prevPv, int &count, std::chrono::_V2::system_clock::time_point start, std::vector< \fBMoveScore\fP > &prevScores)"
.br
.ti -1c
.RI "\fBScore\fP \fBai::quiescence\fP (\fBBoard\fP &board, int depth, int ply_count, \fBScore\fP alpha, \fBScore\fP beta, std::atomic< bool > &stop, int &count, int kickoff)"
.br
.ti -1c
.RI "\fBScore\fP \fBai::alphaBetaSearch\fP (\fBBoard\fP &board, int depth, int ply_count, \fBScore\fP alpha, \fBScore\fP beta, std::atomic< bool > &stop, int &count, \fBNodeType\fP my_node_type, bool is_save)"
.br
.ti -1c
.RI "\fBScore\fP \fBai::zeroWindowSearch\fP (\fBBoard\fP &board, int depth, int ply_count, \fBScore\fP beta, std::atomic< bool > &stop, int &count, \fBNodeType\fP my_node_type)"
.br
.ti -1c
.RI "\fBMoveList\fP< 256 > \fBai::generateMovesOrdered\fP (\fBBoard\fP &board, \fBCMove\fP hash_move, int ply_count, int &num_positive_moves)"
.br
.ti -1c
.RI "bool \fBai::isCheckmateScore\fP (\fBScore\fP sc)"
.br
.ti -1c
.RI "void \fBai::init\fP ()"
.br
.ti -1c
.RI "void \fBai::reset\fP ()"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for S\&.S\&.E\&.H\&.C from the source code\&.
