.TH "include/misc/bits.hpp" 3 "Mon Feb 15 2021" "S.S.E.H.C" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/misc/bits.hpp
.SH SYNOPSIS
.br
.PP
\fC#include <array>\fP
.br
\fC#include 'misc/definitions\&.hpp'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBu64Stack< N >\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBseedRand\fP (int seed)"
.br
.ti -1c
.RI "void \fBtimeSeedRand\fP ()"
.br
.ti -1c
.RI "float \fBrandReal\fP ()"
.br
.ti -1c
.RI "\fBu64\fP \fBrandomBits\fP ()"
.br
.ti -1c
.RI "void \fBinit_bits\fP ()"
.br
.ti -1c
.RI "int \fBhadd\fP (\fBu64\fP x)"
.br
.ti -1c
.RI "void \fBbitscanAll\fP (\fBu64\fP x, \fBu64Stack\fP< 64 > &out_arr)"
.br
.ti -1c
.RI "int \fBbitscanForward\fP (\fBu64\fP x)"
.br
.ti -1c
.RI "int \fBbitscanReverse\fP (\fBu64\fP x)"
.br
.ti -1c
.RI "\fBu64\fP \fBu64FromSquare\fP (\fBSquare\fP s)"
.br
.ti -1c
.RI "\fBSquare\fP \fBu64ToSquare\fP (\fBu64\fP x)"
.br
.ti -1c
.RI "\fBRow\fP \fBu64ToRow\fP (\fBu64\fP x)"
.br
.ti -1c
.RI "\fBCol\fP \fBu64ToCol\fP (\fBu64\fP x)"
.br
.ti -1c
.RI "\fBRow\fP \fBsquareToRow\fP (\fBSquare\fP s)"
.br
.ti -1c
.RI "\fBCol\fP \fBsquareToCol\fP (\fBSquare\fP s)"
.br
.ti -1c
.RI "\fBu64\fP \fBu64FromPair\fP (\fBRow\fP r, \fBCol\fP c)"
.br
.ti -1c
.RI "\fBSquare\fP \fBsquareFromPair\fP (\fBRow\fP r, \fBCol\fP c)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void bitscanAll (\fBu64\fP x, \fBu64Stack\fP< 64 > & out_arr)"

.SS "int bitscanForward (\fBu64\fP x)\fC [inline]\fP"

.SS "int bitscanReverse (\fBu64\fP x)\fC [inline]\fP"

.SS "int hadd (\fBu64\fP x)"

.SS "void init_bits ()"

.SS "\fBu64\fP randomBits ()"

.SS "float randReal ()"

.SS "void seedRand (int seed)"

.SS "\fBSquare\fP squareFromPair (\fBRow\fP r, \fBCol\fP c)\fC [inline]\fP"

.SS "\fBCol\fP squareToCol (\fBSquare\fP s)\fC [inline]\fP"

.SS "\fBRow\fP squareToRow (\fBSquare\fP s)\fC [inline]\fP"

.SS "void timeSeedRand ()"

.SS "\fBu64\fP u64FromPair (\fBRow\fP r, \fBCol\fP c)\fC [inline]\fP"

.SS "\fBu64\fP u64FromSquare (\fBSquare\fP s)\fC [inline]\fP"

.SS "\fBCol\fP u64ToCol (\fBu64\fP x)\fC [inline]\fP"

.SS "\fBRow\fP u64ToRow (\fBu64\fP x)\fC [inline]\fP"

.SS "\fBSquare\fP u64ToSquare (\fBu64\fP x)\fC [inline]\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for S\&.S\&.E\&.H\&.C from the source code\&.
