.TH "board::castle::white" 3 "Fri Feb 19 2021" "S.S.E.H.C" \" -*- nroff -*-
.ad l
.nh
.SH NAME
board::castle::white
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "const int \fBlong_\fP = 0"
.br
.ti -1c
.RI "const int \fBshort_\fP = 1"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "const int board::castle::white::long_ = 0"

.SS "const int board::castle::white::short_ = 1"

.SH "Author"
.PP 
Generated automatically by Doxygen for S\&.S\&.E\&.H\&.C from the source code\&.
