.TH "board::castle::black" 3 "Mon Feb 22 2021" "S.S.E.H.C" \" -*- nroff -*-
.ad l
.nh
.SH NAME
board::castle::black
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "const int \fBlong_\fP = 1"
.br
.ti -1c
.RI "const int \fBshort_\fP = 3"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "const int board::castle::black::long_ = 1"

.SS "const int board::castle::black::short_ = 3"

.SH "Author"
.PP 
Generated automatically by Doxygen for S\&.S\&.E\&.H\&.C from the source code\&.
