.TH "board" 3 "Sat Feb 20 2021" "S.S.E.H.C" \" -*- nroff -*-
.ad l
.nh
.SH NAME
board
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBcastle\fP"
.br
.in -1c
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBState\fP"
.br
.ti -1c
.RI "class \fBStateStack\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBStatus\fP { \fBWhiteWin\fP, \fBBlackWin\fP, \fBDraw\fP, \fBPlaying\fP, \fBStalemate\fP, \fBNotCalculated\fP }"
.br
.in -1c
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBboard::Status\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIWhiteWin \fP\fP
.TP
\fB\fIBlackWin \fP\fP
.TP
\fB\fIDraw \fP\fP
.TP
\fB\fIPlaying \fP\fP
.TP
\fB\fIStalemate \fP\fP
.TP
\fB\fINotCalculated \fP\fP
.SH "Author"
.PP 
Generated automatically by Doxygen for S\&.S\&.E\&.H\&.C from the source code\&.
