.TH "BoardStateStack" 3 "Mon Feb 15 2021" "S.S.E.H.C" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BoardStateStack
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <board\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBBoardStateStack\fP ()"
.br
.ti -1c
.RI "\fBBoardState\fP & \fBpeek\fP ()"
.br
.ti -1c
.RI "\fBBoardState\fP & \fBpeek_at\fP (int i)"
.br
.ti -1c
.RI "bool \fBcan_pop\fP () const"
.br
.ti -1c
.RI "int \fBgetindex\fP () const"
.br
.ti -1c
.RI "void \fBPop\fP ()"
.br
.ti -1c
.RI "void \fBClear\fP ()"
.br
.ti -1c
.RI "void \fBPush\fP (\fBBoardState\fP &state)"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "BoardStateStack::BoardStateStack ()\fC [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "bool BoardStateStack::can_pop () const\fC [inline]\fP"

.SS "void BoardStateStack::Clear ()\fC [inline]\fP"

.SS "int BoardStateStack::getindex () const\fC [inline]\fP"

.SS "\fBBoardState\fP& BoardStateStack::peek ()\fC [inline]\fP"

.SS "\fBBoardState\fP& BoardStateStack::peek_at (int i)\fC [inline]\fP"

.SS "void BoardStateStack::Pop ()\fC [inline]\fP"

.SS "void BoardStateStack::Push (\fBBoardState\fP & state)\fC [inline]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for S\&.S\&.E\&.H\&.C from the source code\&.
