.TH "src/chess/board_debug.cpp" 3 "Mon Feb 22 2021" "S.S.E.H.C" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/chess/board_debug.cpp
.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br
\fC#include 'game/chessboard\&.hpp'\fP
.br
\fC#include 'misc/debug\&.hpp'\fP
.br
\fC#include 'uci/strings\&.hpp'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for S\&.S\&.E\&.H\&.C from the source code\&.
