.TH "board::StateStack" 3 "Sat Feb 20 2021" "S.S.E.H.C" \" -*- nroff -*-
.ad l
.nh
.SH NAME
board::StateStack
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <board_state\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBStateStack\fP ()"
.br
.ti -1c
.RI "\fBboard::State\fP & \fBpeek\fP ()"
.br
.ti -1c
.RI "\fBboard::State\fP & \fBpeek_at\fP (int i)"
.br
.ti -1c
.RI "bool \fBcan_pop\fP () const"
.br
.ti -1c
.RI "int \fBsize\fP () const"
.br
.ti -1c
.RI "void \fBPop\fP ()"
.br
.ti -1c
.RI "void \fBClear\fP ()"
.br
.ti -1c
.RI "void \fBPush\fP (\fBboard::State\fP &state)"
.br
.in -1c
.SH "Detailed Description"
.PP 
A stack implemented with std::vector
.PP
Used to store past states of a chess board that are too heavy to be incrementally updated\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "board::StateStack::StateStack ()\fC [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "bool board::StateStack::can_pop () const\fC [inline]\fP"

.SS "void board::StateStack::Clear ()\fC [inline]\fP"
Clears the stack\&. 
.SS "\fBboard::State\fP& board::StateStack::peek ()\fC [inline]\fP"
Return a reference to the top of the stack\&.
.PP
It's the position immediatly preceding the current one\&. 
.SS "\fBboard::State\fP& board::StateStack::peek_at (int i)\fC [inline]\fP"
Return a reference to a particular index\&. 
.SS "void board::StateStack::Pop ()\fC [inline]\fP"

.SS "void board::StateStack::Push (\fBboard::State\fP & state)\fC [inline]\fP"
Should deference and push copy to stack 
.SS "int board::StateStack::size () const\fC [inline]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for S\&.S\&.E\&.H\&.C from the source code\&.
