.TH "Board" 3 "Mon Feb 15 2021" "S.S.E.H.C" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Board
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <chessboard\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMoveList\fP< 256 > \fBlegal_moves\fP ()"
.br
.ti -1c
.RI "\fBMoveList\fP< 256 > \fBcapture_moves\fP ()"
.br
.ti -1c
.RI "\fBGameStatus\fP \fBstatus\fP ()"
.br
.ti -1c
.RI "bool \fBis_check\fP ()"
.br
.ti -1c
.RI "bool \fBis_checking_move\fP (\fBCMove\fP mv)"
.br
.ti -1c
.RI "\fBCMove\fP \fBmove_from_src_dest\fP (\fBSquare\fP src, \fBSquare\fP dest)"
.br
.ti -1c
.RI "\fBColor\fP \fBget_turn\fP () const"
.br
.ti -1c
.RI "\fBu64\fP \fBget_hash\fP () const"
.br
.ti -1c
.RI "\fBCMove\fP \fBlast_move\fP () const"
.br
.ti -1c
.RI "bool \fBcan_unmake\fP () const"
.br
.ti -1c
.RI "\fBu64\fP \fBoccupancy\fP () const"
.br
.ti -1c
.RI "\fBu64\fP \fBoccupancy\fP (\fBColor\fP color) const"
.br
.ti -1c
.RI "std::string \fBfen\fP () const"
.br
.ti -1c
.RI "void \fBReset\fP ()"
.br
.ti -1c
.RI "void \fBMakeMove\fP (\fBCMove\fP mv)"
.br
.ti -1c
.RI "void \fBUnmakeMove\fP ()"
.br
.ti -1c
.RI "void \fBLoadPosition\fP (\fBPieceType\fP piece_list[64], \fBColor\fP turn, int ep_square, \fBcastle::Rights\fP castling_rights, int fullmove, int halfmove)"
.br
.ti -1c
.RI "void \fBLoadPosition\fP (std::string \fBfen\fP)"
.br
.ti -1c
.RI "void \fBDump\fP ()"
.br
.ti -1c
.RI "\fBBoard\fP ()"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Board::Board ()"

.SH "Member Function Documentation"
.PP 
.SS "bool Board::can_unmake () const"

.SS "\fBMoveList\fP<256> Board::capture_moves ()"

.SS "void Board::Dump ()"

.SS "std::string Board::fen () const"

.SS "\fBu64\fP Board::get_hash () const"

.SS "\fBColor\fP Board::get_turn () const"

.SS "bool Board::is_check ()"

.SS "bool Board::is_checking_move (\fBCMove\fP mv)"

.SS "\fBCMove\fP Board::last_move () const"

.SS "\fBMoveList\fP< 256 > Board::legal_moves ()"

.SS "void Board::LoadPosition (\fBPieceType\fP piece_list[64], \fBColor\fP turn, int ep_square, \fBcastle::Rights\fP castling_rights, int fullmove, int halfmove)"

.SS "void Board::LoadPosition (std::string fen)"

.SS "void Board::MakeMove (\fBCMove\fP mv)"

.SS "\fBCMove\fP Board::move_from_src_dest (\fBSquare\fP src, \fBSquare\fP dest)"

.SS "\fBu64\fP Board::occupancy () const"

.SS "\fBu64\fP Board::occupancy (\fBColor\fP color) const"

.SS "void Board::Reset ()"

.SS "\fBGameStatus\fP Board::status ()"

.SS "void Board::UnmakeMove ()"


.SH "Author"
.PP 
Generated automatically by Doxygen for S\&.S\&.E\&.H\&.C from the source code\&.
