.TH "castle::Rights" 3 "Mon Feb 15 2021" "S.S.E.H.C" \" -*- nroff -*-
.ad l
.nh
.SH NAME
castle::Rights
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <board\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBRights\fP ()"
.br
.ti -1c
.RI "\fBRights\fP (int w_long, int w_short, int b_long, int b_short)"
.br
.ti -1c
.RI "int \fBget\fP (\fBColor\fP color, int direction) const"
.br
.ti -1c
.RI "void \fBSet\fP (\fBColor\fP color, int direction, int value)"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "castle::Rights::Rights ()"

.SS "castle::Rights::Rights (int w_long, int w_short, int b_long, int b_short)"

.SH "Member Function Documentation"
.PP 
.SS "int castle::Rights::get (\fBColor\fP color, int direction) const"

.SS "void castle::Rights::Set (\fBColor\fP color, int direction, int value)"


.SH "Author"
.PP 
Generated automatically by Doxygen for S\&.S\&.E\&.H\&.C from the source code\&.
