.TH "castle" 3 "Mon Feb 15 2021" "S.S.E.H.C" \" -*- nroff -*-
.ad l
.nh
.SH NAME
castle
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBRights\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "const int \fBlong_\fP = 0"
.br
.ti -1c
.RI "const int \fBshort_\fP = 2"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "const int castle::long_ = 0"

.SS "const int castle::short_ = 2"

.SH "Author"
.PP 
Generated automatically by Doxygen for S\&.S\&.E\&.H\&.C from the source code\&.
