.TH "include/game/chessboard.hpp" 3 "Sat Feb 20 2021" "S.S.E.H.C" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/game/chessboard.hpp
.SH SYNOPSIS
.br
.PP
\fC#include 'misc/definitions\&.hpp'\fP
.br
\fC#include 'misc/bits\&.hpp'\fP
.br
\fC#include 'datastructures/board_state\&.hpp'\fP
.br
\fC#include 'datastructures/move_list\&.hpp'\fP
.br
\fC#include 'game/pieces\&.hpp'\fP
.br
\fC#include 'uci/utils\&.hpp'\fP
.br
\fC#include 'misc/debug\&.hpp'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBBoard\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBzobrist\fP"
.br
.ti -1c
.RI " \fBmove_maps\fP"
.br
.ti -1c
.RI " \fBdirection\fP"
.br
.ti -1c
.RI " \fBdirection::rook\fP"
.br
.ti -1c
.RI " \fBdirection::bishop\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBzobrist::init\fP ()"
.br
.ti -1c
.RI "void \fBmove_maps::init\fP ()"
.br
.ti -1c
.RI "bool \fBmove_maps::isAttackedJumping\fP (\fBu64\fP occupancy_map, \fBu64\fP subject, \fBColor\fP subj_turn, \fBu64\fP knights, \fBu64\fP kings, \fBu64\fP pawns)"
.br
.ti -1c
.RI "bool \fBmove_maps::isAttackedSliding\fP (\fBu64\fP occupancy_map, \fBu64\fP subject, \fBu64\fP rooks, \fBu64\fP bishops)"
.br
.ti -1c
.RI "bool \fBmove_maps::isPromotingRank\fP (\fBSquare\fP piece_location, \fBColor\fP color)"
.br
.ti -1c
.RI "bool \fBmove_maps::isStartingRank\fP (\fBSquare\fP piece_location, \fBColor\fP color)"
.br
.ti -1c
.RI "\fBu64\fP \fBmove_maps::oneFileAdjacent\fP (\fBSquare\fP piece_location)"
.br
.ti -1c
.RI "\fBu64\fP \fBmove_maps::pawnCaptures\fP (\fBSquare\fP piece_location, \fBColor\fP color)"
.br
.ti -1c
.RI "\fBu64\fP \fBmove_maps::pawnMoves\fP (\fBSquare\fP piece_location, \fBColor\fP color)"
.br
.ti -1c
.RI "\fBu64\fP \fBmove_maps::pawnDoubleMoves\fP (\fBSquare\fP piece_location, \fBColor\fP color)"
.br
.ti -1c
.RI "\fBu64\fP \fBmove_maps::knightMoves\fP (\fBSquare\fP piece_location)"
.br
.ti -1c
.RI "\fBu64\fP \fBmove_maps::kingMoves\fP (\fBSquare\fP piece_location)"
.br
.ti -1c
.RI "\fBu64\fP \fBmove_maps::bishopMoves\fP (\fBSquare\fP piece_location, \fBu64\fP occupants)"
.br
.ti -1c
.RI "\fBu64\fP \fBmove_maps::rookMoves\fP (\fBSquare\fP piece_location, \fBu64\fP occupants)"
.br
.ti -1c
.RI "\fBu64\fP \fBmove_maps::bishopRay\fP (\fBSquare\fP piece_location, int direction)"
.br
.ti -1c
.RI "\fBu64\fP \fBmove_maps::rookRay\fP (\fBSquare\fP piece_location, int direction)"
.br
.ti -1c
.RI "\fBu64\fP \fBmove_maps::rookRay\fP (\fBSquare\fP piece_location)"
.br
.ti -1c
.RI "\fBu64\fP \fBmove_maps::bishopRay\fP (\fBSquare\fP piece_location)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "const int \fBdirection::rook::n\fP = 0"
.br
.ti -1c
.RI "const int \fBdirection::rook::e\fP = 1"
.br
.ti -1c
.RI "const int \fBdirection::rook::s\fP = 2"
.br
.ti -1c
.RI "const int \fBdirection::rook::w\fP = 3"
.br
.ti -1c
.RI "const int \fBdirection::bishop::nw\fP = 0"
.br
.ti -1c
.RI "const int \fBdirection::bishop::ne\fP = 1"
.br
.ti -1c
.RI "const int \fBdirection::bishop::se\fP = 2"
.br
.ti -1c
.RI "const int \fBdirection::bishop::sw\fP = 3"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for S\&.S\&.E\&.H\&.C from the source code\&.
