.TH "include/game/cmove.hpp" 3 "Sat Feb 20 2021" "S.S.E.H.C" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/game/cmove.hpp
.SH SYNOPSIS
.br
.PP
\fC#include 'misc/bits\&.hpp'\fP
.br
\fC#include 'misc/debug\&.hpp'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBCMove\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBmove_type\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "const int \fBmove_type::NullMove\fP = 0"
.br
.ti -1c
.RI "const int \fBmove_type::Default\fP = 1"
.br
.ti -1c
.RI "const int \fBmove_type::KPromotion\fP = 2"
.br
.ti -1c
.RI "const int \fBmove_type::CastleShort\fP = 3"
.br
.ti -1c
.RI "const int \fBmove_type::BPromotion\fP = 4"
.br
.ti -1c
.RI "const int \fBmove_type::EnPassant\fP = 5"
.br
.ti -1c
.RI "const int \fBmove_type::RPromotion\fP = 6"
.br
.ti -1c
.RI "const int \fBmove_type::DoublePawn\fP = 7"
.br
.ti -1c
.RI "const int \fBmove_type::QPromotion\fP = 8"
.br
.ti -1c
.RI "const int \fBmove_type::CastleLong\fP = 9"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for S\&.S\&.E\&.H\&.C from the source code\&.
