.TH "CMove" 3 "Sat Feb 20 2021" "S.S.E.H.C" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CMove
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <cmove\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "int \fBtype_code\fP () const"
.br
.ti -1c
.RI "bool \fBis_null\fP () const"
.br
.ti -1c
.RI "\fBPieceType\fP \fBpromoting_piece\fP (\fBColor\fP color) const"
.br
.ti -1c
.RI "bool \fBis_promotion\fP () const"
.br
.ti -1c
.RI "bool \fBis_castle\fP () const"
.br
.ti -1c
.RI "\fBSquare\fP \fBsrc_square\fP () const"
.br
.ti -1c
.RI "\fBSquare\fP \fBdest_square\fP () const"
.br
.ti -1c
.RI "\fBu64\fP \fBsrc\fP () const"
.br
.ti -1c
.RI "\fBu64\fP \fBdest\fP () const"
.br
.ti -1c
.RI "\fBCMove\fP (\fBSquare\fP src_, \fBSquare\fP dest_, int type_code_)"
.br
.ti -1c
.RI "\fBCMove\fP ()"
.br
.ti -1c
.RI "bool \fBoperator==\fP (const \fBCMove\fP &other) const"
.br
.ti -1c
.RI "bool \fBoperator!=\fP (const \fBCMove\fP &other) const"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBCMove\fP \fBNullMove\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
'CMove' because of potential naming conflict w/ move op 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "CMove::CMove (\fBSquare\fP src_, \fBSquare\fP dest_, int type_code_)\fC [inline]\fP"

.SS "CMove::CMove ()\fC [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "\fBu64\fP CMove::dest () const\fC [inline]\fP"

.SS "\fBSquare\fP CMove::dest_square () const\fC [inline]\fP"

.SS "bool CMove::is_castle () const\fC [inline]\fP"

.SS "bool CMove::is_null () const\fC [inline]\fP"

.SS "bool CMove::is_promotion () const\fC [inline]\fP"

.SS "static \fBCMove\fP CMove::NullMove ()\fC [inline]\fP, \fC [static]\fP"

.SS "bool CMove::operator!= (const \fBCMove\fP & other) const\fC [inline]\fP"

.SS "bool CMove::operator== (const \fBCMove\fP & other) const\fC [inline]\fP"

.SS "\fBPieceType\fP CMove::promoting_piece (\fBColor\fP color) const\fC [inline]\fP"
Will return the the promotin piece given a color\&. 
.SS "\fBu64\fP CMove::src () const\fC [inline]\fP"

.SS "\fBSquare\fP CMove::src_square () const\fC [inline]\fP"

.SS "int CMove::type_code () const\fC [inline]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for S\&.S\&.E\&.H\&.C from the source code\&.
