.TH "include/misc/definitions.hpp" 3 "Mon Feb 15 2021" "S.S.E.H.C" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/misc/definitions.hpp
.SH SYNOPSIS
.br
.PP
\fC#include <random>\fP
.br
\fC#include <assert\&.h>\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBPieceType\fP   int"
.br
.ti -1c
.RI "#define \fBColor\fP   int"
.br
.ti -1c
.RI "#define \fBSquare\fP   int"
.br
.ti -1c
.RI "#define \fBu64\fP   uint64_t"
.br
.ti -1c
.RI "#define \fBRow\fP   int"
.br
.ti -1c
.RI "#define \fBCol\fP   int"
.br
.ti -1c
.RI "#define \fBScore\fP   int"
.br
.ti -1c
.RI "#define \fBNodeType\fP   int8_t"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmax\fP (int a, int b)"
.br
.ti -1c
.RI "int \fBmin\fP (int a, int b)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "const \fBColor\fP \fBWhite\fP = 0"
.br
.ti -1c
.RI "const \fBColor\fP \fBBlack\fP = 1"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define Col   int"

.SS "#define Color   int"

.SS "#define NodeType   int8_t"

.SS "#define PieceType   int"

.SS "#define Row   int"

.SS "#define Score   int"

.SS "#define Square   int"

.SS "#define u64   uint64_t"

.SH "Function Documentation"
.PP 
.SS "int max (int a, int b)\fC [inline]\fP"

.SS "int min (int a, int b)\fC [inline]\fP"

.SH "Variable Documentation"
.PP 
.SS "const \fBColor\fP Black = 1"

.SS "const \fBColor\fP White = 0"

.SH "Author"
.PP 
Generated automatically by Doxygen for S\&.S\&.E\&.H\&.C from the source code\&.
