.TH "direction" 3 "Fri Feb 19 2021" "S.S.E.H.C" \" -*- nroff -*-
.ad l
.nh
.SH NAME
direction
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBbishop\fP"
.br
.ti -1c
.RI " \fBrook\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Sometimes we care about the specific direction a ray goes for pin checking, or other things\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for S\&.S\&.E\&.H\&.C from the source code\&.
