.TH "direction::bishop" 3 "Mon Feb 15 2021" "S.S.E.H.C" \" -*- nroff -*-
.ad l
.nh
.SH NAME
direction::bishop
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "const int \fBnw\fP = 0"
.br
.ti -1c
.RI "const int \fBne\fP = 1"
.br
.ti -1c
.RI "const int \fBse\fP = 2"
.br
.ti -1c
.RI "const int \fBsw\fP = 3"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "const int direction::bishop::ne = 1"

.SS "const int direction::bishop::nw = 0"

.SS "const int direction::bishop::se = 2"

.SS "const int direction::bishop::sw = 3"

.SH "Author"
.PP 
Generated automatically by Doxygen for S\&.S\&.E\&.H\&.C from the source code\&.
