.TH "direction::rook" 3 "Fri Feb 19 2021" "S.S.E.H.C" \" -*- nroff -*-
.ad l
.nh
.SH NAME
direction::rook
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "const int \fBn\fP = 0"
.br
.ti -1c
.RI "const int \fBe\fP = 1"
.br
.ti -1c
.RI "const int \fBs\fP = 2"
.br
.ti -1c
.RI "const int \fBw\fP = 3"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "const int direction::rook::e = 1"

.SS "const int direction::rook::n = 0"

.SS "const int direction::rook::s = 2"

.SS "const int direction::rook::w = 3"

.SH "Author"
.PP 
Generated automatically by Doxygen for S\&.S\&.E\&.H\&.C from the source code\&.
