.TH "resources/doxygen-bootstrapped-master/example-site/src/example.cpp" 3 "Fri Feb 19 2021" "S.S.E.H.C" \" -*- nroff -*-
.ad l
.nh
.SH NAME
resources/doxygen-bootstrapped-master/example-site/src/example.cpp
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBTest\fP"
.br
.RI "A test class\&. "
.in -1c
.SH "Detailed Description"
.PP 
example file, inspired from https://www.star.bnl.gov/public/comp/sofi/doxygen/docblocks.html 
.SH "Author"
.PP 
Generated automatically by Doxygen for S\&.S\&.E\&.H\&.C from the source code\&.
