.TH "src/chess/hashing.cpp" 3 "Fri Feb 19 2021" "S.S.E.H.C" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/chess/hashing.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'game/chessboard\&.hpp'\fP
.br

.SS "Variables"

.in +1c
.ti -1c
.RI "const int \fBcastle_hash_inds\fP [2][2]"
.br
.ti -1c
.RI "const int \fBep_hash_ind\fP = 64 * 12 + 5"
.br
.ti -1c
.RI "\fBu64\fP \fBHASHES\fP [781]"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "const int castle_hash_inds[2][2]"
\fBInitial value:\fP
.PP
.nf
= {
    {64 * 12 + 1, 64 * 12 + 2},
    {64 * 12 + 3, 64 * 12 + 4},
}
.fi
.SS "const int ep_hash_ind = 64 * 12 + 5"

.SS "\fBu64\fP HASHES[781]"

.SH "Author"
.PP 
Generated automatically by Doxygen for S\&.S\&.E\&.H\&.C from the source code\&.
