.TH "include/uci/interface.hpp" 3 "Mon Feb 22 2021" "S.S.E.H.C" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/uci/interface.hpp
.SH SYNOPSIS
.br
.PP
\fC#include <atomic>\fP
.br
\fC#include <thread>\fP
.br
\fC#include 'uci/strings\&.hpp'\fP
.br
\fC#include 'game/chessboard\&.hpp'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBuci::Interface\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBuci\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBuci::set_debug\fP (bool value)"
.br
.ti -1c
.RI "void \fBuci::listen\fP ()"
.br
.ti -1c
.RI "void \fBuci::sendToUciClient\fP (const std::string &cmd)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for S\&.S\&.E\&.H\&.C from the source code\&.
