.TH "src/uci/main.cpp" 3 "Mon Feb 15 2021" "S.S.E.H.C" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/uci/main.cpp
.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br
\fC#include <chrono>\fP
.br
\fC#include 'game/chessboard\&.hpp'\fP
.br
\fC#include 'uci/strings\&.hpp'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBtestPerft\fP ()"
.br
.ti -1c
.RI "void \fBverbose_print\fP (const std::string &text)"
.br
.ti -1c
.RI "void \fBinit\fP ()"
.br
.ti -1c
.RI "int \fBmain\fP ()"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "bool \fBverbose\fP = true"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void init ()"

.SS "int main ()"

.SS "void testPerft ()"

.SS "void verbose_print (const std::string & text)"
Prints only if the command line verbose flag is set\&. 
.SH "Variable Documentation"
.PP 
.SS "bool verbose = true"

.SH "Author"
.PP 
Generated automatically by Doxygen for S\&.S\&.E\&.H\&.C from the source code\&.
