.TH "md_resources_doxygen_bootstrapped_master_README" 3 "Fri Feb 19 2021" "S.S.E.H.C" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md_resources_doxygen_bootstrapped_master_README \- doxygen-bootstrapped 
Customize doxygen (v1\&.8\&.9) output to use the twitter bootstrap framework (v3\&.3\&.1)
.PP
\fCDemo\fP
.PP
This started as work done by Stratify Labs and was extended further here\&. \fCCredit\fP
.SH "Customizing Doxygen"
.PP
Doxygen provides a handful of ways to \fCcustomize the output\fP\&. The simplest way is to customize the HTML output\&.
.PP
Doxygen allows you to customize the HTML output by modifying a master HTML header, footer and stylesheet\&. You can then include additional stylesheets and javascript files\&. The following command will generate the default Doxygen files\&.
.PP
\fCdoxygen -w html header\&.html footer\&.html customdoxygen\&.css\fP
.PP
Modifying these files alone is not enough to get good Twitter Bootstrap integration\&. Bootstrap requires that certain classes be applied within the HTML\&. For example, a Bootstrap “table” needs to have a class called “table” in order to apply the Bootstrap table formatting\&. We just need to augment the default HTML with these Bootstrap classes\&. To do this, we use the provided doxy-boot\&.js javascript file\&.
.PP
Also, you can augment doxygen’s default stylesheet with a customdoxygen\&.css stylesheet\&. This is where you would place any custom styling such as sticky footers\&.
.SH "How to Integrate"
.PP
To integrate this into your own project tell your doxyfile to use these 4 files in the HTML section (see the example site for an example of each file):
.PP
.IP "\(bu" 2
HTML_HEADER=header\&.html
.IP "  \(bu" 4
Adds a Bootstrap navbar
.IP "  \(bu" 4
Wraps the content in a Bootstrap container/row
.PP

.IP "\(bu" 2
HTML_FOOTER=footer\&.html
.IP "  \(bu" 4
Closes the extra divs opened in the header\&.html
.PP

.IP "\(bu" 2
HTML_EXTRA_STYLESHEET=customdoxygen\&.css
.IP "  \(bu" 4
Adds additional styling such as a sticky footer 
.br

.PP

.IP "\(bu" 2
HTML_EXTRA_FILES=doxy-boot\&.js
.IP "  \(bu" 4
Where the magic happens to augment the HTML with bootstrap
.PP

.PP
.PP
NOTE: The header\&.html file needs to include the Bootstrap css/javascript for this to work\&. This is where you can specify your own bootstrap compilation\&. These files will need to be manually added to the html directory, added as additional files in the doxyfile HTML_EXTRA_FILES section or referenced externally (see example site header\&.html)\&.
.PP
NOTE: If you want to use the customdoxygen\&.css stylesheet from this repository, then you will need to replace the customdoxygen\&.css style sheet generated by the doxygen command above\&. If your customdoxygen\&.css file is in the directory when you run the doxygen command, it will be moved to customdoxygen\&.css\&.bak and you can restore it by overwriting the new version with the backup\&.
.PP
See the example-site directory for a minimal working example\&.
.SS "Todo List"
.IP "\(bu" 2
Menu is not correctly displayed when Doxygen sidebar is enabled\&. 
.PP

