.TH "md_resources_doxygen_dark_theme_master_README" 3 "Fri Feb 19 2021" "S.S.E.H.C" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md_resources_doxygen_dark_theme_master_README \- Doxygen dark theme 
Theme implements dark colors implementation for doxygen documentation generator\&. Selected colors are inspiration from Sublime Text syntax highligher for C language\&.
.SH "Demo"
.PP
Demo of the dark theme is available at https://majerle.eu/documentation/esp_at/html/index.html
.SH "How to use it"
.PP
Usage is very simple\&. You just need to modify your doxygen input file
.PP
.PP
.nf
# Add files to extra stylesheet

HTML_EXTRA_STYLESHEET  = "custom\&.css" \
                         "custom_dark_theme\&.css"
.fi
.PP
.PP
If you wish to use custom made HTML header and footer, enable this feature with
.PP
.PP
.nf
# Custom header
HTML_HEADER            = "html_header\&.html"

# Custom footer
HTML_FOOTER            = "html_footer\&.html"
.fi
.PP
 
