.TH "MiniTableBucket" 3 "Fri Feb 19 2021" "S.S.E.H.C" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MiniTableBucket
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <search\&.hpp>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBu64\fP \fBhash\fP"
.br
.ti -1c
.RI "int8_t \fBdepth\fP"
.br
.ti -1c
.RI "std::array< \fBCMove\fP, 64 > \fBseq\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "int8_t MiniTableBucket::depth"

.SS "\fBu64\fP MiniTableBucket::hash"

.SS "std::array<\fBCMove\fP, 64> MiniTableBucket::seq"


.SH "Author"
.PP 
Generated automatically by Doxygen for S\&.S\&.E\&.H\&.C from the source code\&.
