.TH "MiniTable< N >" 3 "Sat Feb 20 2021" "S.S.E.H.C" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MiniTable< N >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <search\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMiniTable\fP ()"
.br
.ti -1c
.RI "\fBMiniTableBucket\fP * \fBfind\fP (\fBu64\fP hashval)"
.br
.ti -1c
.RI "int \fBppm\fP ()"
.br
.ti -1c
.RI "\fBMiniTableBucket\fP * \fBend\fP ()"
.br
.ti -1c
.RI "void \fBclear\fP ()"
.br
.ti -1c
.RI "void \fBinsert\fP (\fBu64\fP hashval, int depth, std::array< \fBCMove\fP, 64 > *moveseq)"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<int N> \fBMiniTable\fP< N >::\fBMiniTable\fP ()\fC [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "template<int N> void \fBMiniTable\fP< N >::clear ()\fC [inline]\fP"

.SS "template<int N> \fBMiniTableBucket\fP* \fBMiniTable\fP< N >::end ()\fC [inline]\fP"

.SS "template<int N> \fBMiniTableBucket\fP* \fBMiniTable\fP< N >::find (\fBu64\fP hashval)\fC [inline]\fP"

.SS "template<int N> void \fBMiniTable\fP< N >::insert (\fBu64\fP hashval, int depth, std::array< \fBCMove\fP, 64 > * moveseq)\fC [inline]\fP"

.SS "template<int N> int \fBMiniTable\fP< N >::ppm ()\fC [inline]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for S\&.S\&.E\&.H\&.C from the source code\&.
