.TH "MoveScore" 3 "Sat Feb 20 2021" "S.S.E.H.C" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MoveScore
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <search\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMoveScore\fP (\fBCMove\fP mv0, \fBScore\fP score0)"
.br
.ti -1c
.RI "bool \fBoperator<\fP (const \fBMoveScore\fP other) const"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBCMove\fP \fBmv\fP"
.br
.ti -1c
.RI "\fBScore\fP \fBscore\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
A tuple that contains a move and a corresponding score\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "MoveScore::MoveScore (\fBCMove\fP mv0, \fBScore\fP score0)\fC [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "bool MoveScore::operator< (const \fBMoveScore\fP other) const\fC [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "\fBCMove\fP MoveScore::mv"

.SS "\fBScore\fP MoveScore::score"


.SH "Author"
.PP 
Generated automatically by Doxygen for S\&.S\&.E\&.H\&.C from the source code\&.
