.TH "move_cache" 3 "Mon Feb 15 2021" "S.S.E.H.C" \" -*- nroff -*-
.ad l
.nh
.SH NAME
move_cache
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBinit\fP ()"
.br
.ti -1c
.RI "\fBu64\fP \fBpawnCaptures\fP (\fBu64\fP piece_location, \fBColor\fP color, \fBu64\fP occupants)"
.br
.ti -1c
.RI "\fBu64\fP \fBpawnCaptures\fP (\fBSquare\fP piece_location, \fBColor\fP color, \fBu64\fP occupants)"
.br
.ti -1c
.RI "\fBu64\fP \fBpawnMoves\fP (\fBu64\fP piece_location, \fBColor\fP color, \fBu64\fP occupants)"
.br
.ti -1c
.RI "\fBu64\fP \fBpawnMoves\fP (\fBSquare\fP piece_location, \fBColor\fP color, \fBu64\fP occupants)"
.br
.ti -1c
.RI "\fBu64\fP \fBpawnDoubleMoves\fP (\fBu64\fP piece_location, \fBColor\fP color, \fBu64\fP occupants)"
.br
.ti -1c
.RI "\fBu64\fP \fBpawnDoubleMoves\fP (\fBSquare\fP piece_location, \fBColor\fP color, \fBu64\fP occupants)"
.br
.ti -1c
.RI "\fBu64\fP \fBknightMoves\fP (\fBu64\fP piece_location, \fBu64\fP occupants)"
.br
.ti -1c
.RI "\fBu64\fP \fBknightMoves\fP (\fBSquare\fP piece_location, \fBu64\fP occupants)"
.br
.ti -1c
.RI "\fBu64\fP \fBkingMoves\fP (\fBu64\fP piece_location, \fBu64\fP occupants)"
.br
.ti -1c
.RI "\fBu64\fP \fBkingMoves\fP (\fBSquare\fP piece_location, \fBu64\fP occupants)"
.br
.ti -1c
.RI "\fBu64\fP \fBbishopMoves\fP (\fBu64\fP piece_location, \fBu64\fP occupants)"
.br
.ti -1c
.RI "\fBu64\fP \fBbishopMoves\fP (\fBSquare\fP piece_location, \fBu64\fP occupants)"
.br
.ti -1c
.RI "\fBu64\fP \fBrookMoves\fP (\fBu64\fP piece_location, \fBu64\fP occupants)"
.br
.ti -1c
.RI "\fBu64\fP \fBrookMoves\fP (\fBSquare\fP piece_location, \fBu64\fP occupants)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBu64\fP move_cache::bishopMoves (\fBSquare\fP piece_location, \fBu64\fP occupants)"

.SS "\fBu64\fP move_cache::bishopMoves (\fBu64\fP piece_location, \fBu64\fP occupants)"

.SS "void move_cache::init ()"
may be unecessary 
.SS "\fBu64\fP move_cache::kingMoves (\fBSquare\fP piece_location, \fBu64\fP occupants)"

.SS "\fBu64\fP move_cache::kingMoves (\fBu64\fP piece_location, \fBu64\fP occupants)"

.SS "\fBu64\fP move_cache::knightMoves (\fBSquare\fP piece_location, \fBu64\fP occupants)"

.SS "\fBu64\fP move_cache::knightMoves (\fBu64\fP piece_location, \fBu64\fP occupants)"

.SS "\fBu64\fP move_cache::pawnCaptures (\fBSquare\fP piece_location, \fBColor\fP color, \fBu64\fP occupants)"

.SS "\fBu64\fP move_cache::pawnCaptures (\fBu64\fP piece_location, \fBColor\fP color, \fBu64\fP occupants)"

.SS "\fBu64\fP move_cache::pawnDoubleMoves (\fBSquare\fP piece_location, \fBColor\fP color, \fBu64\fP occupants)"

.SS "\fBu64\fP move_cache::pawnDoubleMoves (\fBu64\fP piece_location, \fBColor\fP color, \fBu64\fP occupants)"

.SS "\fBu64\fP move_cache::pawnMoves (\fBSquare\fP piece_location, \fBColor\fP color, \fBu64\fP occupants)"

.SS "\fBu64\fP move_cache::pawnMoves (\fBu64\fP piece_location, \fBColor\fP color, \fBu64\fP occupants)"

.SS "\fBu64\fP move_cache::rookMoves (\fBSquare\fP piece_location, \fBu64\fP occupants)"

.SS "\fBu64\fP move_cache::rookMoves (\fBu64\fP piece_location, \fBu64\fP occupants)"

.SH "Author"
.PP 
Generated automatically by Doxygen for S\&.S\&.E\&.H\&.C from the source code\&.
