.TH "MoveScoreTuple" 3 "Mon Feb 15 2021" "S.S.E.H.C" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MoveScoreTuple
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <search\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMoveScoreTuple\fP (\fBCMove\fP mv0, int score0)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBCMove\fP \fBmv\fP"
.br
.ti -1c
.RI "int \fBscore\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
This file contains data structures pertaining to \fBAI\fP hash tables, etc A tuple that contains a move and a corresponding score\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "MoveScoreTuple::MoveScoreTuple (\fBCMove\fP mv0, int score0)\fC [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "\fBCMove\fP MoveScoreTuple::mv"

.SS "int MoveScoreTuple::score"


.SH "Author"
.PP 
Generated automatically by Doxygen for S\&.S\&.E\&.H\&.C from the source code\&.
