.TH "include/misc/perft.hpp" 3 "Sat Feb 20 2021" "S.S.E.H.C" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/misc/perft.hpp
.SH SYNOPSIS
.br
.PP
\fC#include 'game/chessboard\&.hpp'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBperft::Counter\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBperft\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBperft::perft\fP (\fBBoard\fP &board_, int depth, Counter &counter)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for S\&.S\&.E\&.H\&.C from the source code\&.
