.TH "PerftCounter" 3 "Mon Feb 15 2021" "S.S.E.H.C" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PerftCounter
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <perft\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPerftCounter\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBu64\fP \fBnodes\fP"
.br
.ti -1c
.RI "\fBu64\fP \fBcaptures\fP"
.br
.ti -1c
.RI "\fBu64\fP \fBep\fP"
.br
.ti -1c
.RI "\fBu64\fP \fBcastles\fP"
.br
.ti -1c
.RI "\fBu64\fP \fBpromotions\fP"
.br
.ti -1c
.RI "\fBu64\fP \fBchecks\fP"
.br
.ti -1c
.RI "\fBu64\fP \fBcheckmates\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "PerftCounter::PerftCounter ()\fC [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "\fBu64\fP PerftCounter::captures"

.SS "\fBu64\fP PerftCounter::castles"

.SS "\fBu64\fP PerftCounter::checkmates"

.SS "\fBu64\fP PerftCounter::checks"

.SS "\fBu64\fP PerftCounter::ep"

.SS "\fBu64\fP PerftCounter::nodes"

.SS "\fBu64\fP PerftCounter::promotions"


.SH "Author"
.PP 
Generated automatically by Doxygen for S\&.S\&.E\&.H\&.C from the source code\&.
