.TH "perft::Counter" 3 "Fri Feb 19 2021" "S.S.E.H.C" \" -*- nroff -*-
.ad l
.nh
.SH NAME
perft::Counter
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <perft\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCounter\fP ()"
.br
.ti -1c
.RI "void \fBDump\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBnodes\fP"
.br
.ti -1c
.RI "int \fBcaptures\fP"
.br
.ti -1c
.RI "int \fBep\fP"
.br
.ti -1c
.RI "int \fBcastles\fP"
.br
.ti -1c
.RI "int \fBpromotions\fP"
.br
.ti -1c
.RI "int \fBchecks\fP"
.br
.ti -1c
.RI "int \fBcheckmates\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "perft::Counter::Counter ()\fC [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "void perft::Counter::Dump ()\fC [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "int perft::Counter::captures"

.SS "int perft::Counter::castles"

.SS "int perft::Counter::checkmates"

.SS "int perft::Counter::checks"

.SS "int perft::Counter::ep"

.SS "int perft::Counter::nodes"

.SS "int perft::Counter::promotions"


.SH "Author"
.PP 
Generated automatically by Doxygen for S\&.S\&.E\&.H\&.C from the source code\&.
