.TH "src/misc/perft.cpp" 3 "Sat Feb 20 2021" "S.S.E.H.C" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/misc/perft.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'misc/perft\&.hpp'\fP
.br
\fC#include 'uci/strings\&.hpp'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for S\&.S\&.E\&.H\&.C from the source code\&.
