.TH "perft" 3 "Sat Feb 20 2021" "S.S.E.H.C" \" -*- nroff -*-
.ad l
.nh
.SH NAME
perft
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBCounter\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBperft\fP (\fBBoard\fP &board_, int depth, \fBCounter\fP &counter)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void perft::perft (\fBBoard\fP & board_, int depth, \fBperft::Counter\fP & counter)"

.SH "Author"
.PP 
Generated automatically by Doxygen for S\&.S\&.E\&.H\&.C from the source code\&.
