.TH "piece" 3 "Mon Feb 22 2021" "S.S.E.H.C" \" -*- nroff -*-
.ad l
.nh
.SH NAME
piece
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBblack\fP"
.br
.ti -1c
.RI " \fBcolorless\fP"
.br
.ti -1c
.RI " \fBwhite\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBto_colorless\fP (\fBPieceType\fP piece)"
.br
.ti -1c
.RI "bool \fBis_empty\fP (\fBPieceType\fP piece)"
.br
.ti -1c
.RI "bool \fBis_pawn\fP (\fBPieceType\fP piece)"
.br
.ti -1c
.RI "bool \fBis_king\fP (\fBPieceType\fP piece)"
.br
.ti -1c
.RI "bool \fBis_knight\fP (\fBPieceType\fP piece)"
.br
.ti -1c
.RI "bool \fBis_bishop\fP (\fBPieceType\fP piece)"
.br
.ti -1c
.RI "bool \fBis_rook\fP (\fBPieceType\fP piece)"
.br
.ti -1c
.RI "bool \fBis_queen\fP (\fBPieceType\fP piece)"
.br
.ti -1c
.RI "\fBPieceType\fP \fBflip\fP (\fBPieceType\fP piece)"
.br
.ti -1c
.RI "\fBPieceType\fP \fBget_pawn\fP (\fBColor\fP color)"
.br
.ti -1c
.RI "\fBPieceType\fP \fBget_bishop\fP (\fBColor\fP color)"
.br
.ti -1c
.RI "\fBPieceType\fP \fBget_knight\fP (\fBColor\fP color)"
.br
.ti -1c
.RI "\fBPieceType\fP \fBget_rook\fP (\fBColor\fP color)"
.br
.ti -1c
.RI "\fBPieceType\fP \fBget_queen\fP (\fBColor\fP color)"
.br
.ti -1c
.RI "\fBPieceType\fP \fBget_king\fP (\fBColor\fP color)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "const \fBPieceType\fP \fBEmptyPiece\fP = \-1"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBPieceType\fP piece::flip (\fBPieceType\fP piece)\fC [inline]\fP"

.SS "\fBPieceType\fP piece::get_bishop (\fBColor\fP color)\fC [inline]\fP"

.SS "\fBPieceType\fP piece::get_king (\fBColor\fP color)\fC [inline]\fP"

.SS "\fBPieceType\fP piece::get_knight (\fBColor\fP color)\fC [inline]\fP"

.SS "\fBPieceType\fP piece::get_pawn (\fBColor\fP color)\fC [inline]\fP"

.SS "\fBPieceType\fP piece::get_queen (\fBColor\fP color)\fC [inline]\fP"

.SS "\fBPieceType\fP piece::get_rook (\fBColor\fP color)\fC [inline]\fP"

.SS "bool piece::is_bishop (\fBPieceType\fP piece)\fC [inline]\fP"

.SS "bool piece::is_empty (\fBPieceType\fP piece)\fC [inline]\fP"

.SS "bool piece::is_king (\fBPieceType\fP piece)\fC [inline]\fP"

.SS "bool piece::is_knight (\fBPieceType\fP piece)\fC [inline]\fP"

.SS "bool piece::is_pawn (\fBPieceType\fP piece)\fC [inline]\fP"

.SS "bool piece::is_queen (\fBPieceType\fP piece)\fC [inline]\fP"

.SS "bool piece::is_rook (\fBPieceType\fP piece)\fC [inline]\fP"

.SS "int piece::to_colorless (\fBPieceType\fP piece)\fC [inline]\fP"

.SH "Variable Documentation"
.PP 
.SS "const \fBPieceType\fP piece::EmptyPiece = \-1"

.SH "Author"
.PP 
Generated automatically by Doxygen for S\&.S\&.E\&.H\&.C from the source code\&.
