.TH "piece" 3 "Mon Feb 15 2021" "S.S.E.H.C" \" -*- nroff -*-
.ad l
.nh
.SH NAME
piece
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBblack\fP"
.br
.ti -1c
.RI " \fBwhite\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "const \fBPieceType\fP \fBEmptyPiece\fP = \-1"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "const \fBPieceType\fP piece::EmptyPiece = \-1"

.SH "Author"
.PP 
Generated automatically by Doxygen for S\&.S\&.E\&.H\&.C from the source code\&.
