.TH "src/chess/pieces.cpp" 3 "Mon Feb 22 2021" "S.S.E.H.C" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/chess/pieces.cpp
.SH SYNOPSIS
.br
.PP
\fC#include <string>\fP
.br
\fC#include 'misc/definitions\&.hpp'\fP
.br
\fC#include 'game/pieces\&.hpp'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBgetMaterialValue\fP (\fBPieceType\fP piece)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "const int \fBMATERIAL_TABLE\fP [13] = {100, 350, 350, 525, 1000, 0}"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int getMaterialValue (\fBPieceType\fP piece)"

.SH "Variable Documentation"
.PP 
.SS "const int MATERIAL_TABLE[13] = {100, 350, 350, 525, 1000, 0}"

.SH "Author"
.PP 
Generated automatically by Doxygen for S\&.S\&.E\&.H\&.C from the source code\&.
