.TH "piece::black" 3 "Mon Feb 15 2021" "S.S.E.H.C" \" -*- nroff -*-
.ad l
.nh
.SH NAME
piece::black
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "const \fBPieceType\fP \fBpawn\fP = (0 << 1) + 1"
.br
.ti -1c
.RI "const \fBPieceType\fP \fBknight\fP = (1 << 1) + 1"
.br
.ti -1c
.RI "const \fBPieceType\fP \fBbishop\fP = (2 << 1) + 1"
.br
.ti -1c
.RI "const \fBPieceType\fP \fBrook\fP = (3 << 1) + 1"
.br
.ti -1c
.RI "const \fBPieceType\fP \fBqueen\fP = (4 << 1) + 1"
.br
.ti -1c
.RI "const \fBPieceType\fP \fBking\fP = (5 << 1) + 1"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "const \fBPieceType\fP piece::black::bishop = (2 << 1) + 1"

.SS "const \fBPieceType\fP piece::black::king = (5 << 1) + 1"

.SS "const \fBPieceType\fP piece::black::knight = (1 << 1) + 1"

.SS "const \fBPieceType\fP piece::black::pawn = (0 << 1) + 1"

.SS "const \fBPieceType\fP piece::black::queen = (4 << 1) + 1"

.SS "const \fBPieceType\fP piece::black::rook = (3 << 1) + 1"

.SH "Author"
.PP 
Generated automatically by Doxygen for S\&.S\&.E\&.H\&.C from the source code\&.
