.TH "piece::white" 3 "Sat Feb 20 2021" "S.S.E.H.C" \" -*- nroff -*-
.ad l
.nh
.SH NAME
piece::white
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "const \fBPieceType\fP \fBpawn\fP = (0 << 1)"
.br
.ti -1c
.RI "const \fBPieceType\fP \fBknight\fP = (1 << 1)"
.br
.ti -1c
.RI "const \fBPieceType\fP \fBbishop\fP = (2 << 1)"
.br
.ti -1c
.RI "const \fBPieceType\fP \fBrook\fP = (3 << 1)"
.br
.ti -1c
.RI "const \fBPieceType\fP \fBqueen\fP = (4 << 1)"
.br
.ti -1c
.RI "const \fBPieceType\fP \fBking\fP = (5 << 1)"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "const \fBPieceType\fP piece::white::bishop = (2 << 1)"

.SS "const \fBPieceType\fP piece::white::king = (5 << 1)"

.SS "const \fBPieceType\fP piece::white::knight = (1 << 1)"

.SS "const \fBPieceType\fP piece::white::pawn = (0 << 1)"

.SS "const \fBPieceType\fP piece::white::queen = (4 << 1)"

.SS "const \fBPieceType\fP piece::white::rook = (3 << 1)"

.SH "Author"
.PP 
Generated automatically by Doxygen for S\&.S\&.E\&.H\&.C from the source code\&.
