.TH "piece::colorless" 3 "Fri Feb 19 2021" "S.S.E.H.C" \" -*- nroff -*-
.ad l
.nh
.SH NAME
piece::colorless
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "const int \fBpawn\fP = 0"
.br
.ti -1c
.RI "const int \fBknight\fP = 1"
.br
.ti -1c
.RI "const int \fBbishop\fP = 2"
.br
.ti -1c
.RI "const int \fBrook\fP = 3"
.br
.ti -1c
.RI "const int \fBqueen\fP = 4"
.br
.ti -1c
.RI "const int \fBking\fP = 5"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "const int piece::colorless::bishop = 2"

.SS "const int piece::colorless::king = 5"

.SS "const int piece::colorless::knight = 1"

.SS "const int piece::colorless::pawn = 0"

.SS "const int piece::colorless::queen = 4"

.SS "const int piece::colorless::rook = 3"

.SH "Author"
.PP 
Generated automatically by Doxygen for S\&.S\&.E\&.H\&.C from the source code\&.
