.TH "profile.py" 3 "Mon Feb 22 2021" "S.S.E.H.C" \" -*- nroff -*-
.ad l
.nh
.SH NAME
profile.py
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBprofile\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBprofile\&.fname\fP = str(datetime\&.datetime\&.now()\&.strftime('%I\-%M\-%S\-%d\-%m\-%Y'))"
.br
.ti -1c
.RI "string \fBprofile\&.logname\fP = fname + '\&.txt'"
.br
.ti -1c
.RI "string \fBprofile\&.valgrind\fP = 'valgrind \-\-tool=callgrind \-\-callgrind\-out\-file={} \&./build/apps/ssehc \-\-benchmark'\&.format(logname)"
.br
.ti -1c
.RI "string \fBprofile\&.imgname\fP = fname + '\&.svg'"
.br
.ti -1c
.RI "string \fBprofile\&.gprof2dot\fP = 'gprof2dot \-f callgrind {} | dot \-Tsvg \-o {}'\&.format(logname, imgname)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for S\&.S\&.E\&.H\&.C from the source code\&.
