.TH "profile" 3 "Sat Feb 20 2021" "S.S.E.H.C" \" -*- nroff -*-
.ad l
.nh
.SH NAME
profile
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBfname\fP = str(datetime\&.datetime\&.now()\&.strftime('%I\-%M\-%S\-%d\-%m\-%Y'))"
.br
.ti -1c
.RI "string \fBlogname\fP = \fBfname\fP + '\&.txt'"
.br
.ti -1c
.RI "string \fBvalgrind\fP = 'valgrind \-\-tool=callgrind \-\-callgrind\-out\-file={} \&./build/apps/ssehc \-\-benchmark'\&.format(\fBlogname\fP)"
.br
.ti -1c
.RI "string \fBimgname\fP = \fBfname\fP + '\&.svg'"
.br
.ti -1c
.RI "string \fBgprof2dot\fP = 'gprof2dot \-f callgrind {} | dot \-Tsvg \-o {}'\&.format(\fBlogname\fP, \fBimgname\fP)"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "profile\&.fname = str(datetime\&.datetime\&.now()\&.strftime('%I\-%M\-%S\-%d\-%m\-%Y'))"

.SS "string profile\&.gprof2dot = 'gprof2dot \-f callgrind {} | dot \-Tsvg \-o {}'\&.format(\fBlogname\fP, \fBimgname\fP)"

.SS "string profile\&.imgname = \fBfname\fP + '\&.svg'"

.SS "string profile\&.logname = \fBfname\fP + '\&.txt'"

.SS "string profile\&.valgrind = 'valgrind \-\-tool=callgrind \-\-callgrind\-out\-file={} \&./build/apps/ssehc \-\-benchmark'\&.format(\fBlogname\fP)"

.SH "Author"
.PP 
Generated automatically by Doxygen for S\&.S\&.E\&.H\&.C from the source code\&.
