.TH "src/datastructures/search.cpp" 3 "Fri Feb 19 2021" "S.S.E.H.C" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/datastructures/search.cpp
.SH SYNOPSIS
.br
.PP
\fC#include <queue>\fP
.br
\fC#include 'datastructures/search\&.hpp'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBCMove\fP \fBpopMin\fP (std::vector< \fBMoveScore\fP > &vec)"
.br
.ti -1c
.RI "\fBCMove\fP \fBpopMax\fP (std::vector< \fBMoveScore\fP > &vec)"
.br
.ti -1c
.RI "void \fBsortMoves\fP (std::vector< \fBMoveScore\fP > &vec)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBCMove\fP popMax (std::vector< \fBMoveScore\fP > & vec)"

.SS "\fBCMove\fP popMin (std::vector< \fBMoveScore\fP > & vec)"

.SS "void sortMoves (std::vector< \fBMoveScore\fP > & vec)"

.SH "Author"
.PP 
Generated automatically by Doxygen for S\&.S\&.E\&.H\&.C from the source code\&.
