.TH "include/datastructures/search.hpp" 3 "Mon Feb 22 2021" "S.S.E.H.C" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/datastructures/search.hpp
.SH SYNOPSIS
.br
.PP
\fC#include 'misc/definitions\&.hpp'\fP
.br
\fC#include 'game/chessboard\&.hpp'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBMoveScore\fP"
.br
.ti -1c
.RI "struct \fBTableNode\fP"
.br
.ti -1c
.RI "struct \fBTableBucket\fP"
.br
.ti -1c
.RI "class \fBTranspositionTable< N >\fP"
.br
.ti -1c
.RI "struct \fBMiniTableBucket\fP"
.br
.ti -1c
.RI "class \fBMiniTable< N >\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "const \fBNodeType\fP \fBPV\fP = 0"
.br
.ti -1c
.RI "const \fBNodeType\fP \fBCut\fP = 1"
.br
.ti -1c
.RI "const \fBNodeType\fP \fBAll\fP = 2"
.br
.ti -1c
.RI "const int \fBSCORE_MIN\fP = std::numeric_limits<int>::\fBmin\fP()"
.br
.ti -1c
.RI "const int \fBSCORE_MAX\fP = std::numeric_limits<int>::\fBmax\fP()"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "const \fBNodeType\fP All = 2"

.SS "const \fBNodeType\fP Cut = 1"

.SS "const \fBNodeType\fP PV = 0"

.SS "const int SCORE_MAX = std::numeric_limits<int>::\fBmax\fP()"

.SS "const int SCORE_MIN = std::numeric_limits<int>::\fBmin\fP()"

.SH "Author"
.PP 
Generated automatically by Doxygen for S\&.S\&.E\&.H\&.C from the source code\&.
