.TH "src/uci/strings.cpp" 3 "Fri Feb 19 2021" "S.S.E.H.C" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/uci/strings.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'uci/strings\&.hpp'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "std::string \fBpieceToStringFen\fP (\fBPieceType\fP piece)"
.br
.ti -1c
.RI "\fBPieceType\fP \fBpieceFromStringFen\fP (std::string val)"
.br
.ti -1c
.RI "std::string \fBmoveToUCIAlgebraic\fP (\fBCMove\fP mv)"
.br
.ti -1c
.RI "std::string \fBpieceToStringLower\fP (\fBPieceType\fP piece)"
.br
.ti -1c
.RI "std::string \fBsquareName\fP (\fBu64\fP square)"
.br
.ti -1c
.RI "std::string \fBsquareName\fP (\fBSquare\fP square)"
.br
.ti -1c
.RI "\fBu64\fP \fBu64FromName\fP (std::string alg)"
.br
.ti -1c
.RI "\fBSquare\fP \fBsquareFromName\fP (std::string alg)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "std::string moveToUCIAlgebraic (\fBCMove\fP mv)"

.SS "\fBPieceType\fP pieceFromStringFen (std::string val)"

.SS "std::string pieceToStringFen (\fBPieceType\fP piece)"

.SS "std::string pieceToStringLower (\fBPieceType\fP piece)"

.SS "\fBSquare\fP squareFromName (std::string alg)"

.SS "std::string squareName (\fBSquare\fP square)"

.SS "std::string squareName (\fBu64\fP square)"

.SS "\fBu64\fP u64FromName (std::string alg)"

.SH "Author"
.PP 
Generated automatically by Doxygen for S\&.S\&.E\&.H\&.C from the source code\&.
