.TH "TableBucket" 3 "Mon Feb 22 2021" "S.S.E.H.C" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TableBucket
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <search\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTableBucket\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBTableNode\fP \fBnode\fP"
.br
.ti -1c
.RI "\fBScore\fP \fBscore\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "TableBucket::TableBucket ()\fC [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "\fBTableNode\fP TableBucket::node"

.SS "\fBScore\fP TableBucket::score"


.SH "Author"
.PP 
Generated automatically by Doxygen for S\&.S\&.E\&.H\&.C from the source code\&.
