.TH "Test" 3 "Fri Feb 19 2021" "S.S.E.H.C" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Test \- A test class\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum \fBTEnum\fP { \fBTVal1\fP, \fBTVal2\fP, \fBTVal3\fP }"
.br
.RI "An enum\&. "
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTest\fP ()"
.br
.RI "A constructor\&. "
.ti -1c
.RI "\fB~Test\fP ()"
.br
.RI "A destructor\&. "
.ti -1c
.RI "int \fBtestMe\fP (int a, const char *s)"
.br
.RI "a normal member taking two arguments and returning an integer value\&. "
.ti -1c
.RI "virtual void \fBtestMeToo\fP (char c1, char c2)=0"
.br
.RI "A pure virtual member\&. "
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "enum \fBTest::TEnum\fP * \fBenumPtr\fP"
.br
.ti -1c
.RI "enum \fBTest::TEnum\fP \fBenumVar\fP"
.br
.ti -1c
.RI "int \fBpublicVar\fP"
.br
.RI "a public variable\&. "
.ti -1c
.RI "int(* \fBhandler\fP )(int a, int b)"
.br
.RI "a function variable\&. "
.in -1c
.SH "Detailed Description"
.PP 
A test class\&. 

A more elaborate class description\&.
.PP
\fBTodo\fP
.RS 4
add some functionality 
.RE
.PP

.SH "Member Enumeration Documentation"
.PP 
.SS "enum \fBTest::TEnum\fP"

.PP
An enum\&. More detailed enum description\&. 
.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fITVal1 \fP\fP
enum value TVal1\&. 
.TP
\fB\fITVal2 \fP\fP
enum value TVal2\&. 
.TP
\fB\fITVal3 \fP\fP
enum value TVal3\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Test::Test ()"

.PP
A constructor\&. A more elaborate description of the constructor\&. 
.SS "Test::~Test ()"

.PP
A destructor\&. A more elaborate description of the destructor\&. 
.PP
\fBWarning\fP
.RS 4
beware of destruction! 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "int Test::testMe (int a, const char * s)"

.PP
a normal member taking two arguments and returning an integer value\&. 
.PP
\fBParameters\fP
.RS 4
\fIa\fP an integer argument\&. 
.br
\fIs\fP a constant character pointer\&. 
.RE
.PP
\fBSee also\fP
.RS 4
\fBTest()\fP 
.PP
\fB~Test()\fP 
.PP
\fBtestMeToo()\fP 
.PP
\fBpublicVar()\fP 
.RE
.PP
\fBReturns\fP
.RS 4
The test results 
.RE
.PP

.SS "virtual void Test::testMeToo (char c1, char c2)\fC [pure virtual]\fP"

.PP
A pure virtual member\&. 
.PP
\fBSee also\fP
.RS 4
\fBtestMe()\fP 
.RE
.PP
\fBParameters\fP
.RS 4
\fIc1\fP the first argument\&. 
.br
\fIc2\fP the second argument\&. 
.RE
.PP

.SH "Member Data Documentation"
.PP 
.SS "enum \fBTest::TEnum\fP * Test::enumPtr"
enum pointer\&. Details\&. 
.SS "enum \fBTest::TEnum\fP Test::enumVar"
enum variable\&. Details\&. 
.SS "int(* Test::handler) (int a, int b)"

.PP
a function variable\&. Details\&. 
.SS "int Test::publicVar"

.PP
a public variable\&. Details\&.
.PP
\fBNote\fP
.RS 4
A small note\&. 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for S\&.S\&.E\&.H\&.C from the source code\&.
