.TH "TranspositionTable< N >" 3 "Sat Feb 20 2021" "S.S.E.H.C" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TranspositionTable< N >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <search\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTranspositionTable\fP ()"
.br
.ti -1c
.RI "int \fBppm\fP ()"
.br
.ti -1c
.RI "\fBTableBucket\fP * \fBfind\fP (\fBTableNode\fP &node)"
.br
.ti -1c
.RI "\fBTableBucket\fP * \fBend\fP ()"
.br
.ti -1c
.RI "void \fBinsert\fP (\fBTableNode\fP &node, \fBScore\fP score)"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<int N> \fBTranspositionTable\fP< N >::\fBTranspositionTable\fP ()\fC [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "template<int N> \fBTableBucket\fP* \fBTranspositionTable\fP< N >::end ()\fC [inline]\fP"

.SS "template<int N> \fBTableBucket\fP* \fBTranspositionTable\fP< N >::find (\fBTableNode\fP & node)\fC [inline]\fP"

.SS "template<int N> void \fBTranspositionTable\fP< N >::insert (\fBTableNode\fP & node, \fBScore\fP score)\fC [inline]\fP"

.SS "template<int N> int \fBTranspositionTable\fP< N >::ppm ()\fC [inline]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for S\&.S\&.E\&.H\&.C from the source code\&.
