.TH "u64Stack< N >" 3 "Mon Feb 15 2021" "S.S.E.H.C" \" -*- nroff -*-
.ad l
.nh
.SH NAME
u64Stack< N >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <bits\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBu64Stack\fP ()"
.br
.ti -1c
.RI "void \fBAppend\fP (\fBu64\fP value)"
.br
.ti -1c
.RI "void \fBClear\fP ()"
.br
.ti -1c
.RI "int \fBlen\fP () const"
.br
.ti -1c
.RI "\fBu64\fP \fBoperator[]\fP (int index) const"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<int N>
.br
class u64Stack< N >"
A stack of u64 values, with a length limited to N\&.
.PP
Ideally, only to be traversed upwards\&.
.PP
Returned by \fBbitscanAll()\fP\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<int N> \fBu64Stack\fP< N >::\fBu64Stack\fP ()\fC [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "template<int N> void \fBu64Stack\fP< N >::Append (\fBu64\fP value)\fC [inline]\fP"

.SS "template<int N> void \fBu64Stack\fP< N >::Clear ()\fC [inline]\fP"

.SS "template<int N> int \fBu64Stack\fP< N >::len () const\fC [inline]\fP"

.SS "template<int N> \fBu64\fP \fBu64Stack\fP< N >::operator[] (int index) const\fC [inline]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for S\&.S\&.E\&.H\&.C from the source code\&.
