.TH "uci" 3 "Mon Feb 22 2021" "S.S.E.H.C" \" -*- nroff -*-
.ad l
.nh
.SH NAME
uci
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBInterface\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBset_debug\fP (bool value)"
.br
.ti -1c
.RI "void \fBlisten\fP ()"
.br
.ti -1c
.RI "void \fBsendToUciClient\fP (const std::string &cmd)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void uci::listen ()"
Kick off the engine\&. 
.SS "void uci::sendToUciClient (const std::string & cmd)"
prints a command to stdout 
.SS "void uci::set_debug (bool value)"
Implementing the UCI debug option\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for S\&.S\&.E\&.H\&.C from the source code\&.
