.TH "uci::Interface" 3 "Sat Feb 20 2021" "S.S.E.H.C" \" -*- nroff -*-
.ad l
.nh
.SH NAME
uci::Interface
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <interface\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBInterface\fP ()"
.br
.ti -1c
.RI "\fB~Interface\fP ()"
.br
.ti -1c
.RI "void \fBThink\fP ()"
.br
.ti -1c
.RI "void \fBStopThinking\fP ()"
.br
.ti -1c
.RI "void \fBDelayStop\fP (int msecs)"
.br
.ti -1c
.RI "void \fBStartThinking\fP (bool inf, int msecs)"
.br
.ti -1c
.RI "void \fBRecieveCommand\fP (std::string cmd)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "std::atomic< bool > \fBnot_thinking\fP {true}"
.br
.ti -1c
.RI "std::atomic< bool > \fBstop_timer\fP {false}"
.br
.ti -1c
.RI "\fBCMove\fP \fBbestMove\fP"
.br
.ti -1c
.RI "\fBBoard\fP \fBboard\fP"
.br
.ti -1c
.RI "std::thread \fBsearch_thread\fP"
.br
.ti -1c
.RI "std::thread \fBtimer_thread\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "uci::Interface::Interface ()"
Default constructor\&. 
.SS "uci::Interface::~Interface ()"
Destructor; stops threads gracefully\&. 
.SH "Member Function Documentation"
.PP 
.SS "void uci::Interface::DelayStop (int msecs)"
This stops the think thread after a certain number of ms\&. 
.SS "void uci::Interface::RecieveCommand (std::string cmd)"
Recieve a command from the client\&. 
.SS "void uci::Interface::StartThinking (bool inf, int msecs)"
Launches the search thread either with a fixed time in milliseconds or infinitely long\&. 
.SS "void uci::Interface::StopThinking ()"
This stops the think thread\&. 
.SS "void uci::Interface::Think ()"
This runs the AB search\&. 
.SH "Member Data Documentation"
.PP 
.SS "\fBCMove\fP uci::Interface::bestMove"

.SS "\fBBoard\fP uci::Interface::board"

.SS "std::atomic<bool> uci::Interface::not_thinking {true}"
this will stop the search if set to true
.PP
we pass this into the AB search\&. 
.SS "std::thread uci::Interface::search_thread"

.SS "std::atomic<bool> uci::Interface::stop_timer {false}"
this will stop the timer that in turn stops the search if there is a fixed time set\&. 
.SS "std::thread uci::Interface::timer_thread"


.SH "Author"
.PP 
Generated automatically by Doxygen for S\&.S\&.E\&.H\&.C from the source code\&.
