.TH "include/uci/utils.hpp" 3 "Mon Feb 15 2021" "S.S.E.H.C" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/uci/utils.hpp
.SH SYNOPSIS
.br
.PP
\fC#include <string>\fP
.br
\fC#include <vector>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBsendToUciClient\fP (const std::string &cmd)"
.br
.ti -1c
.RI "std::vector< std::string > \fBtokenize\fP (std::string in_string)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void sendToUciClient (const std::string & cmd)"

.SS "std::vector<std::string> tokenize (std::string in_string)"

.SH "Author"
.PP 
Generated automatically by Doxygen for S\&.S\&.E\&.H\&.C from the source code\&.
