.TH "src/uci/utils.cpp" 3 "Sat Feb 20 2021" "S.S.E.H.C" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/uci/utils.cpp
.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br
\fC#include <sstream>\fP
.br
\fC#include <iterator>\fP
.br
\fC#include 'uci/utils\&.hpp'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBsendToUciClient\fP (const std::string &cmd)"
.br
.ti -1c
.RI "std::vector< std::string > \fBtokenize\fP (std::string in_string)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void sendToUciClient (const std::string & cmd)"

.SS "std::vector<std::string> tokenize (std::string in_string)"
sentence -> list of words 
.SH "Author"
.PP 
Generated automatically by Doxygen for S\&.S\&.E\&.H\&.C from the source code\&.
