.TH "include/misc/version.hpp" 3 "Sat Feb 20 2021" "S.S.E.H.C" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/misc/version.hpp
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "const int \fBversion_major\fP = 0"
.br
.ti -1c
.RI "const int \fBversion_minor\fP = 1"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "const int version_major = 0"

.SS "const int version_minor = 1"

.SH "Author"
.PP 
Generated automatically by Doxygen for S\&.S\&.E\&.H\&.C from the source code\&.
